spring:
  redis:
    host: 172.23.102.55
    port: 6379
    password: 123456

master:
  jdbc-url: jdbc:mysql://172.23.102.55:3306/tssp_manage?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: tssp
  password: Tssp123

tssp:
  routing:
    ip: http://172.23.102.55:20000

spring.boot.admin.client:
  url: "http://172.23.102.55:10010/admin"