spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - 172.23.102.55:9092
          zk-nodes:
          - 172.23.102.55:2181
          auto-add-partitions: true
          auto-create-topics: true
      bindings:
        analysis: 
          group: tssp-analysis
          destination: analysis
          consumer: 
            auto-commit-offset: false
            auto-rebalance-enabled: true
              
  data:
    mongodb:
      #uri: mongo://172.23.105.211:27017/tssp
      host: 172.23.102.55
      port: 27017
      database: tssp
      #authentication-database: tssp
      #username: tssp
      #password: tssp123
spring.boot.admin.client:
  url: "http://172.23.102.55:10010/admin"